### ISSUE TITLE
アイデア出し

### ISSUE THREAD

**Issue by yona3** [yona3/okicafe#1]
![IMG_1025](https://github.com/yona3/okicafe/assets/160720324/dee60832-2335-4f02-8cb7-ca75666a127c)

**Comment by toume-rui** [comment]
![Uploading IMG_1025.jpg…]()

**Comment by toume-rui** [comment]
![Uploading IMG_1025.jpg…]()

**Comment by toume-rui** [comment]
![Image](https://github.com/yona3/okicafe/assets/160720324/470541be-a5fe-4270-a903-832b6638ee8c)
